name: pathoscreen
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12.9
  - pip=25.2
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.3.2
  - pyyaml=6.0.2
  - tqdm=4.67.1
  - rdkit=2025.03.6
  - scikit-learn=1.7.2
  - joblib=1.5.2
  - matplotlib-base=3.10.6
  - seaborn=0.13.2
  - xgboost=3.0.1
  - optuna=4.5.0
  - sqlalchemy=2.0.43
  - pip:
      - torch==2.3.1 --index-url https://download.pytorch.org/whl/cu121
      - torchvision==0.18.1 --index-url https://download.pytorch.org/whl/cu121
      - torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121
      - easydict==1.13
      - requests==2.32.5
      - requests-cache==1.2.1
      - pubchempy==1.0.5
      - chembl-webresource-client==0.10.9
      - gensim==4.3.3